version: "3"

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "80:80"
    depends_on:
      - runner-game
      - keyboard-drum
      - bubble-game
      - we-teach
    networks:
      - app-network

  runner-game:
    build:
      context: ./runner-game
    expose:
      - "80"
    networks:
      - app-network

  keyboard-drum:
    build:
      context: ./keyboard-drum
    expose:
      - "80"
    networks:
      - app-network

  bubble-game:
    build:
      context: ./bubble-game
    expose:
      - "80"
    networks:
      - app-network

  we-teach:
    build:
      context: .
    expose:
      - "80"
    networks:
      - app-network
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - UPLOADTHING_SECRET=${UPLOADTHING_SECRET}
      - UPLOADTHING_APP_ID=${UPLOADTHING_APP_ID}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MUX_TOKEN_ID=${MUX_TOKEN_ID}
      - MUX_TOKEN_SECRET=${MUX_TOKEN_SECRET}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXT_PUBLIC_PUBLISHER_ID=${NEXT_PUBLIC_PUBLISHER_ID}
      - NEXT_PUBLIC_PUBLISHER_EMAIL=${NEXT_PUBLIC_PUBLISHER_EMAIL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_URL_INTERNAL=${NEXTAUTH_URL_INTERNAL}

networks:
  app-network:
    driver: bridge
# #version: '3'

# services:
#   nextjs:
#     image: mkpatidar/weteach
#     build:
#       context: .
#     container_name: weteach
#     ports:
#       - "3000:3000"
#     environment:
#       - DATABASE_URL=mysql://avnadmin:AVNS_3nq0SANq86aiJj-Htyv@we-teach-we-teach.f.aivencloud.com:13765/defaultdb?ssl-mode=REQUIRED
#       - UPLOADTHING_SECRET=sk_live_aba5174ed3629765b042b2335e526b982bac2953fb68b3865da914ce340d3a7f
#       - UPLOADTHING_APP_ID=4u43ux1nfu
#       - NEXTAUTH_SECRET=w2m1ty5gsHw7Ho+CRHWW7W5+69JQ0QhtjZ/k4vRmlKQ=
#       - GOOGLE_CLIENT_ID=161609457199-43b189vkp7bcbk4bpjpq6mvg4flv5e0v.apps.googleusercontent.com
#       - GOOGLE_CLIENT_SECRET=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
#       - MUX_TOKEN_ID=bc0e8d23-800e-42bc-af83-fa93e23eba19
#       - MUX_TOKEN_SECRET=vZuK1LFzZAZN/MEWqNuRW/8qGT7VW7ESqNOrGDkUW0gVpxsOWBZa77S9ToG2C4Ll8Fr3dS1JSB9
#       - STRIPE_API_KEY=sk_test_51O1oIQSAjQ6IO23pntlMjZTOq8fLizSjUqbu2YdDrQgSGKeespfvgzeU9wytCMciEsExP6DDpbNyWVsMh6fisDpT00ByBm6SO9
#       - NEXT_PUBLIC_APP_URL=http://localhost:80
#       - STRIPE_WEBHOOK_SECRET=whsec_a3728ae977126d9adb92efcdf6b92a4095d585f07eea195f3947bcc11b9b6654
#       - NEXT_PUBLIC_PUBLISHER_ID=1
#       - NEXT_PUBLIC_PUBLISHER_EMAIL=demo@gmail.com
#       - AUTH_TRUST_HOST=true
