import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToasterProvider from "@/components/providers/ToasterProvider";
import ConfettiProvider from "@/components/providers/ConfettiProvider";
import { SessionProvider } from "next-auth/react";

// import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <body className={`${inter.className} bg-gray-600 text-white`}>
        <ConfettiProvider />
        <ToasterProvider />
        <SessionProvider
          // Re-fetches session when window is focused
          refetchOnWindowFocus={true}
        >
          {children}
        </SessionProvider>
      </body>
    </html>
    // </ClerkProvider>
  );
}
